# GET http://localhost:4004/v2/odata/v4/CPMaster/CompareCDwithSF(pid=800)

GET http://localhost:4004/v2/odata/v4/CPMaster/CompareCDwithSF(pid='909')
###

GET http://localhost:4004/v2/odata/v4/CPMaster/FetchJRData()
###

GET http://localhost:4004/v2/odata/v4/CPMaster/MatchingCandidate(Jid='1105')
###

GET http://localhost:4004/v2/odata/v4/CPMaster/AddNewCandi()
###

GET http://localhost:4004/v2/odata/v4/CPMaster/DataSummary()